# Default config. REMEMBER TO SET 'PASSWORD'
modem_url: 'http://admin:PASSWORD@192.168.8.1/'

# use zabbix config from host /etc/zabbix/zabbix_agentd.conf (ServerActive=...)
# zabbix-server need to allow zabbix trap connections)
zabbix_sender_settings: 'use_config=True'
#ZabbixSender('use_config=True')
#ZabbixSender('hostname')
#ZabbixSender('IP ADDRESS')


# needs to be same as 'Host name' configured in Zabbix front end
monitored_hostname: 'mymodem.local'

api_poll_config: 'api_huawei_lte_4g_config.yml'

log_level: 'WARNING'

# testing / debugging variables
print_zabbix_send: false
do_zabbix_send: true
do_it_once: false
