key_prefix:
 - name: device.signal
   polling_interval:
    - '60': ['rsrq', 'rsrp', 'rssi', 'sinr', 'txpower']
    - '600': ['pci' ,'cell_id','band','nei_cellid']
    - '3600': ['ims','tac','mode', "rrc_status",'plmn','lteulfreq',
               'ltedlfreq', 'enodeb_id', 'ulbandwidth','dlbandwidth' ]
 - name: device.information
   polling_interval:
     - '3600': ['DeviceName' ,'SerialNumber' ,'Imei' ,'Imsi' ,'Iccid','Msisdn',
                'HardwareVersion' ,'SoftwareVersion' ,'WebUIVersion' ,'MacAddress1' ,'MacAddress2',
                'WanIPAddress' ,'wan_dns_address' ,'WanIPv6Address' ,'wan_ipv6_dns_address' ,
                'ProductFamily' ,'Classify' ,'supportmode' ,'workmode' ,'submask' ,
                'Mccmnc' ,'iniversion' ,'uptime' ,'ImeiSvn' ,'WifiMacAddrWl0' ,'WifiMacAddrWl1',
                'spreadname_en' ,'spreadname_zh']
   inventory:
     - 'DeviceName'
     - 'SerialNumber'
     - 'Imei'
     - 'Imsi'
     - 'HardwareVersion'
     - 'SoftwareVersion'
     - 'WebUIVersion'
     - 'MacAddress1'
     - 'MacAddress2'
     - 'WifiMacAddrWl0'
     - 'WifiMacAddrWl1'
     - 'spreadname_en'
 - name: device.information
   polling_interval:
     - 3600: ['UnreadMessage' ,'SmsStorageFull' ,'OnlineUpdateStatus' ,'SimOperEvent']
# Note: 'OnlineUpdateStatus': '14'
#
 - name: user.history_login
   polling_interval:
     - 3600: ['last_login_state' ,'last_login_time' ,'last_login_ipaddr']
       # this seems to be that last web login info
       # last_login_state: -1 means one ip is blocked 3 failed from same IP
